#pragma once

#define DISPLAY_TIME_BLACKSCREEN_SCENE 2.0f
#define DISPLAY_TIME_SPLASH_SCENE 5.0f
#define LEVELUP_SCENE_TIME 5.5f
#define TRANSITION_TIME 1.0f
#define MARBLE_SPAWN_FREQUENCY 0.05f
#define MARBLECHARGES_SPAWN_FREQUENCY 0.1f


